# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Update src/maxdiffusion/dependency_versions_table.py based on the dependencies
defined in dependencies/requirements/base_requirements/requirements.txt.
"""

import os
import re

def main():
    requirements_file = "dependencies/requirements/generated_requirements/requirements.txt"
    target_file = "src/maxdiffusion/dependency_versions_table.py"

    if not os.path.exists(requirements_file):
        print(f"Error: {requirements_file} not found.")
        return

    deps = {}
    with open(requirements_file, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith(("#", "--")):
                continue

            # Simple regex to extract package name and version
            # This covers: pkg, pkg>=1.0, pkg==1.0, pkg @ https://...
            match = re.match(r"^([^!=<>~@\s]+)(?:.*)$", line)
            if match:
                pkg_name = match.group(1)
                deps[pkg_name] = line

    entries = "\n".join([f'    "{k}": "{v}",' for k, v in sorted(deps.items())])
    content = [
        "# THIS FILE HAS BEEN AUTOGENERATED. To update:",
        "# 1. modify the requirements in dependencies/requirements/generated_requirements/requirements.txt",
        "# 2. run `make deps_table_update` or `python utils/update_dependency_table.py`",
        "deps = {",
        entries,
        "}",
        "",
    ]

    print(f"Updating {target_file}")
    with open(target_file, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(content))

if __name__ == "__main__":
    main()
