#!/usr/bin/env bash
set -euo pipefail

CONFIG="src/maxdiffusion/configs/base_wan_animate_27b.yml"
VENV_PATH="/data/maxdiffusion-work/maxdiffusion-venv"
OUTPUT_ROOT="/data/maxdiffusion-work/outputs/wan-animate-sweeps"
RUN_PREFIX="wananimate-sweep"
ENABLE_PROFILER="True"
SKIP_JAX_DISTRIBUTED_SYSTEM="True"
NUM_FRAMES_OVERRIDE=""
PER_DEVICE_BATCH_SIZE="1"
DRY_RUN=0
declare -a SCENARIOS=()
declare -a EXTRA_OVERRIDES=()

usage() {
  cat <<'EOF'
Usage:
  scripts/run_wan_animate_parallelism_sweep.sh [options]

Runs a sequence of WAN Animate inference jobs with different parallelism layouts.
Each run gets its own output directory, TensorBoard trace directory, and log file.

Default scenarios:
  context8:1:1:8:1
  context4_tensor2:1:1:4:2
  context2_tensor4:1:1:2:4
  context2_fsdp4:1:4:2:1
  fsdp4_tensor2:1:4:1:2
  cp2_fsdp2_tp2:1:2:2:2
  fsdp8:1:8:1:1

Scenario format:
  name:data:fsdp:context:tensor

Options:
  --config <path>            Config file to run
  --venv <path>              Virtualenv root containing bin/python
  --output-root <path>       Root folder for the sweep session
  --run-prefix <prefix>      Prefix used in run names and session directory
  --num-frames <int>         Override num_frames for all runs
  --per-device-batch-size <n>
                             Override per_device_batch_size for all runs
  --scenario <spec>          Add a scenario; may be repeated
  --extra-override <k=v>     Extra config override; may be repeated
  --no-profiler              Disable profiler for all runs
  --dry-run                  Print commands without executing them
  -h, --help                 Show this help

Example:
  scripts/run_wan_animate_parallelism_sweep.sh \
    --run-prefix wananimate-xprof \
    --scenario context8:1:1:8:1 \
    --scenario context4_tensor2:1:1:4:2
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --config)
      CONFIG="${2:-}"
      shift 2
      ;;
    --venv)
      VENV_PATH="${2:-}"
      shift 2
      ;;
    --output-root)
      OUTPUT_ROOT="${2:-}"
      shift 2
      ;;
    --run-prefix)
      RUN_PREFIX="${2:-}"
      shift 2
      ;;
    --num-frames)
      NUM_FRAMES_OVERRIDE="${2:-}"
      shift 2
      ;;
    --per-device-batch-size)
      PER_DEVICE_BATCH_SIZE="${2:-}"
      shift 2
      ;;
    --scenario)
      SCENARIOS+=("${2:-}")
      shift 2
      ;;
    --extra-override)
      EXTRA_OVERRIDES+=("${2:-}")
      shift 2
      ;;
    --no-profiler)
      ENABLE_PROFILER="False"
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ ${#SCENARIOS[@]} -eq 0 ]]; then
  SCENARIOS=(
    "context8:1:1:8:1"
    "context4_tensor2:1:1:4:2"
    "context2_tensor4:1:1:2:4"
    "context2_fsdp4:1:4:2:1"
    "fsdp4_tensor2:1:4:1:2"
    "cp2_fsdp2_tp2:1:2:2:2"
    "fsdp8:1:8:1:1"
  )
fi

if [[ ! -f "${CONFIG}" ]]; then
  echo "Config not found: ${CONFIG}" >&2
  exit 1
fi

if [[ ! -x "${VENV_PATH}/bin/python" ]]; then
  echo "Python not found in venv: ${VENV_PATH}/bin/python" >&2
  exit 1
fi

DEVICE_COUNT="$("${VENV_PATH}/bin/python" - <<'PY'
import jax
print(jax.device_count())
PY
)"

if [[ -z "${DEVICE_COUNT}" ]]; then
  echo "Unable to determine JAX device count from ${VENV_PATH}/bin/python" >&2
  exit 1
fi

GLOBAL_BATCH_SIZE="$("${VENV_PATH}/bin/python" - <<PY
per_device_batch_size = float("${PER_DEVICE_BATCH_SIZE}")
device_count = int("${DEVICE_COUNT}")
global_batch_size = per_device_batch_size * device_count
if not global_batch_size.is_integer():
    raise SystemExit(
        f"per_device_batch_size={per_device_batch_size} with device_count={device_count} "
        f"does not produce a whole-number global batch size"
    )
print(int(global_batch_size))
PY
)"

SESSION_ID="$(date -u +%Y%m%d-%H%M%S)"
SESSION_ROOT="${OUTPUT_ROOT%/}/${RUN_PREFIX}-${SESSION_ID}"
LOG_DIR="${SESSION_ROOT}/logs"
mkdir -p "${LOG_DIR}"

SUMMARY_TSV="${SESSION_ROOT}/summary.tsv"
COMMANDS_SH="${SESSION_ROOT}/commands.sh"

{
  printf "scenario\trun_name\tstatus\tduration_seconds\toutput_dir\ttensorboard_dir\tlog_file\n"
} > "${SUMMARY_TSV}"

{
  echo "#!/usr/bin/env bash"
  echo "set -euo pipefail"
  echo
  echo "# Generated by scripts/run_wan_animate_parallelism_sweep.sh"
  echo "# Session root: ${SESSION_ROOT}"
  echo
} > "${COMMANDS_SH}"

echo "Sweep session root: ${SESSION_ROOT}"
echo "Summary file: ${SUMMARY_TSV}"
echo "Commands file: ${COMMANDS_SH}"
echo "TensorBoard root: ${SESSION_ROOT}"
echo "Detected JAX devices: ${DEVICE_COUNT}"
echo "per_device_batch_size: ${PER_DEVICE_BATCH_SIZE}"
echo "Global batch size: ${GLOBAL_BATCH_SIZE}"
echo

for scenario_spec in "${SCENARIOS[@]}"; do
  IFS=":" read -r scenario_name data_parallelism fsdp_parallelism context_parallelism tensor_parallelism <<< "${scenario_spec}"
  if [[ -z "${scenario_name}" || -z "${data_parallelism}" || -z "${fsdp_parallelism}" || -z "${context_parallelism}" || -z "${tensor_parallelism}" ]]; then
    echo "Invalid scenario: ${scenario_spec}" >&2
    echo "Expected format: name:data:fsdp:context:tensor" >&2
    exit 1
  fi

  scenario_device_product=$((data_parallelism * fsdp_parallelism * context_parallelism * tensor_parallelism))
  if [[ "${scenario_device_product}" -ne "${DEVICE_COUNT}" ]]; then
    echo "Invalid scenario ${scenario_name}: data*fsdp*context*tensor=${scenario_device_product}, expected ${DEVICE_COUNT}" >&2
    exit 1
  fi

  batch_shard_count=$((data_parallelism * fsdp_parallelism))
  if (( GLOBAL_BATCH_SIZE % batch_shard_count != 0 )); then
    echo "Invalid scenario ${scenario_name}: global batch size ${GLOBAL_BATCH_SIZE} is not divisible by data*fsdp=${batch_shard_count}" >&2
    echo "Set --per-device-batch-size so global_batch_size=device_count*per_device_batch_size is divisible by data*fsdp." >&2
    exit 1
  fi

  run_name="${RUN_PREFIX}-${scenario_name}"
  artifacts_root="${SESSION_ROOT}/artifacts"
  run_output_dir="${artifacts_root}/${run_name}"
  run_tensorboard_dir="${run_output_dir}/tensorboard"
  log_file="${LOG_DIR}/${run_name}.log"

  cmd=(
    "${VENV_PATH}/bin/python"
    "src/maxdiffusion/generate_wan_animate.py"
    "${CONFIG}"
    "run_name=${run_name}"
    "output_dir=${run_output_dir}"
    "enable_profiler=${ENABLE_PROFILER}"
    "skip_jax_distributed_system=${SKIP_JAX_DISTRIBUTED_SYSTEM}"
    "per_device_batch_size=${PER_DEVICE_BATCH_SIZE}"
    "ici_data_parallelism=${data_parallelism}"
    "ici_fsdp_parallelism=${fsdp_parallelism}"
    "ici_context_parallelism=${context_parallelism}"
    "ici_tensor_parallelism=${tensor_parallelism}"
  )

  if [[ -n "${NUM_FRAMES_OVERRIDE}" ]]; then
    cmd+=("num_frames=${NUM_FRAMES_OVERRIDE}")
  fi

  for extra_override in "${EXTRA_OVERRIDES[@]}"; do
    cmd+=("${extra_override}")
  done

  printf "%q " "${cmd[@]}" >> "${COMMANDS_SH}"
  printf "\n\n" >> "${COMMANDS_SH}"

  echo "========================================================================"
  echo "Scenario: ${scenario_name}"
  echo "Run name: ${run_name}"
  echo "Parallelism: data=${data_parallelism}, fsdp=${fsdp_parallelism}, context=${context_parallelism}, tensor=${tensor_parallelism}"
  echo "Batching: per_device=${PER_DEVICE_BATCH_SIZE}, global=${GLOBAL_BATCH_SIZE}, data*fsdp=${batch_shard_count}"
  echo "Output dir: ${run_output_dir}"
  echo "TensorBoard dir: ${run_tensorboard_dir}"
  echo "Log file: ${log_file}"
  echo "========================================================================"

  if [[ "${DRY_RUN}" -eq 1 ]]; then
    printf "DRY RUN: "
    printf "%q " "${cmd[@]}"
    printf "\n\n"
    printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
      "${scenario_name}" \
      "${run_name}" \
      "DRY_RUN" \
      "0" \
      "${run_output_dir}" \
      "${run_tensorboard_dir}" \
      "${log_file}" >> "${SUMMARY_TSV}"
    continue
  fi

  start_ts="$(date +%s)"
  set +e
  (
    echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] Starting ${run_name}"
    printf "Command: "
    printf "%q " "${cmd[@]}"
    printf "\n"
    "${cmd[@]}"
  ) 2>&1 | tee "${log_file}"
  exit_code=${PIPESTATUS[0]}
  set -e
  end_ts="$(date +%s)"
  duration="$((end_ts - start_ts))"

  if [[ "${exit_code}" -eq 0 ]]; then
    status="OK"
  else
    status="FAIL(${exit_code})"
  fi

  printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
    "${scenario_name}" \
    "${run_name}" \
    "${status}" \
    "${duration}" \
    "${run_output_dir}" \
    "${run_tensorboard_dir}" \
    "${log_file}" >> "${SUMMARY_TSV}"

  echo
done

chmod +x "${COMMANDS_SH}"

echo "Sweep complete."
echo "Summary: ${SUMMARY_TSV}"
echo "Commands: ${COMMANDS_SH}"
echo "To inspect traces tomorrow:"
echo "  tensorboard --logdir=${artifacts_root:-${SESSION_ROOT}/artifacts}"
